---
galaxy_info:
  author: Prakhar Srivastava
  description: LiteMaaS deployment role for OpenShift - Cloud Agnostic
  company: Red Hat
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: OpenShift
      versions:
        - "4.12"
        - "4.13"
        - "4.14"
        - "4.15"
  galaxy_tags:
    - openshift
    - kubernetes
    - ai
    - litellm
    - rhdp

dependencies: []
